version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "crates/ollama-node-agent/packaging/linux"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "crates/ollama-router/ui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "site"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm:
        patterns:
          - "*"
